/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StylistId = IDL.Nat;
export const ServiceId = IDL.Nat;
export const BookingRequest = IDL.Record({
  'startTime' : IDL.Text,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'stylistId' : StylistId,
  'clientEmail' : IDL.Text,
  'clientPhone' : IDL.Text,
  'serviceId' : ServiceId,
});
export const AppointmentId = IDL.Nat;
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'startTime' : IDL.Text,
  'status' : AppointmentStatus,
  'referenceNumber' : IDL.Text,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'stylistId' : StylistId,
  'createdAt' : Timestamp,
  'clientEmail' : IDL.Text,
  'clientPhone' : IDL.Text,
  'serviceId' : ServiceId,
});
export const BookingResult = IDL.Variant({
  'ok' : Appointment,
  'err' : IDL.Text,
});
export const TimeSlot = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'date' : IDL.Text,
  'stylistId' : StylistId,
  'isBooked' : IDL.Bool,
});
export const Service = IDL.Record({
  'id' : ServiceId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'price' : IDL.Nat,
});
export const StylistPublic = IDL.Record({
  'id' : StylistId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'available' : IDL.Bool,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func([BookingRequest], [BookingResult], []),
  'cancelAppointment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'claimAdmin' : IDL.Func([], [IDL.Bool], []),
  'completeAppointment' : IDL.Func([AppointmentId], [IDL.Bool], []),
  'getAdmin' : IDL.Func([], [IDL.Principal], ['query']),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAppointmentByReference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Appointment)],
      ['query'],
    ),
  'getAvailableSlots' : IDL.Func(
      [IDL.Text, StylistId],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getStylists' : IDL.Func([], [IDL.Vec(StylistPublic)], ['query']),
  'updateServicePricing' : IDL.Func([ServiceId, IDL.Nat], [IDL.Bool], []),
  'updateStylistAvailability' : IDL.Func([StylistId, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StylistId = IDL.Nat;
  const ServiceId = IDL.Nat;
  const BookingRequest = IDL.Record({
    'startTime' : IDL.Text,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'stylistId' : StylistId,
    'clientEmail' : IDL.Text,
    'clientPhone' : IDL.Text,
    'serviceId' : ServiceId,
  });
  const AppointmentId = IDL.Nat;
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'startTime' : IDL.Text,
    'status' : AppointmentStatus,
    'referenceNumber' : IDL.Text,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'stylistId' : StylistId,
    'createdAt' : Timestamp,
    'clientEmail' : IDL.Text,
    'clientPhone' : IDL.Text,
    'serviceId' : ServiceId,
  });
  const BookingResult = IDL.Variant({ 'ok' : Appointment, 'err' : IDL.Text });
  const TimeSlot = IDL.Record({
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'date' : IDL.Text,
    'stylistId' : StylistId,
    'isBooked' : IDL.Bool,
  });
  const Service = IDL.Record({
    'id' : ServiceId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const StylistPublic = IDL.Record({
    'id' : StylistId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'available' : IDL.Bool,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func([BookingRequest], [BookingResult], []),
    'cancelAppointment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'claimAdmin' : IDL.Func([], [IDL.Bool], []),
    'completeAppointment' : IDL.Func([AppointmentId], [IDL.Bool], []),
    'getAdmin' : IDL.Func([], [IDL.Principal], ['query']),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAppointmentByReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Appointment)],
        ['query'],
      ),
    'getAvailableSlots' : IDL.Func(
        [IDL.Text, StylistId],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getStylists' : IDL.Func([], [IDL.Vec(StylistPublic)], ['query']),
    'updateServicePricing' : IDL.Func([ServiceId, IDL.Nat], [IDL.Bool], []),
    'updateStylistAvailability' : IDL.Func(
        [StylistId, IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };