/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : AppointmentId,
  'startTime' : string,
  'status' : AppointmentStatus,
  'referenceNumber' : string,
  'clientName' : string,
  'date' : string,
  'stylistId' : StylistId,
  'createdAt' : Timestamp,
  'clientEmail' : string,
  'clientPhone' : string,
  'serviceId' : ServiceId,
}
export type AppointmentId = bigint;
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface BookingRequest {
  'startTime' : string,
  'clientName' : string,
  'date' : string,
  'stylistId' : StylistId,
  'clientEmail' : string,
  'clientPhone' : string,
  'serviceId' : ServiceId,
}
export type BookingResult = { 'ok' : Appointment } |
  { 'err' : string };
export interface Service {
  'id' : ServiceId,
  'name' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'price' : bigint,
}
export type ServiceId = bigint;
export type StylistId = bigint;
export interface StylistPublic {
  'id' : StylistId,
  'bio' : string,
  'name' : string,
  'available' : boolean,
}
export interface TimeSlot {
  'startTime' : string,
  'endTime' : string,
  'date' : string,
  'stylistId' : StylistId,
  'isBooked' : boolean,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'bookAppointment' : ActorMethod<[BookingRequest], BookingResult>,
  'cancelAppointment' : ActorMethod<[string], boolean>,
  'claimAdmin' : ActorMethod<[], boolean>,
  'completeAppointment' : ActorMethod<[AppointmentId], boolean>,
  'getAdmin' : ActorMethod<[], Principal>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAppointmentByReference' : ActorMethod<[string], [] | [Appointment]>,
  'getAvailableSlots' : ActorMethod<[string, StylistId], Array<TimeSlot>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getStylists' : ActorMethod<[], Array<StylistPublic>>,
  'updateServicePricing' : ActorMethod<[ServiceId, bigint], boolean>,
  'updateStylistAvailability' : ActorMethod<[StylistId, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];