/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ServiceId = bigint;
export type Timestamp = bigint;
export interface TimeSlot {
    startTime: string;
    endTime: string;
    date: string;
    stylistId: StylistId;
    isBooked: boolean;
}
export interface StylistPublic {
    id: StylistId;
    bio: string;
    name: string;
    available: boolean;
}
export interface BookingRequest {
    startTime: string;
    clientName: string;
    date: string;
    stylistId: StylistId;
    clientEmail: string;
    clientPhone: string;
    serviceId: ServiceId;
}
export interface Service {
    id: ServiceId;
    name: string;
    description: string;
    durationMinutes: bigint;
    price: bigint;
}
export type BookingResult = {
    __kind__: "ok";
    ok: Appointment;
} | {
    __kind__: "err";
    err: string;
};
export type AppointmentId = bigint;
export interface Appointment {
    id: AppointmentId;
    startTime: string;
    status: AppointmentStatus;
    referenceNumber: string;
    clientName: string;
    date: string;
    stylistId: StylistId;
    createdAt: Timestamp;
    clientEmail: string;
    clientPhone: string;
    serviceId: ServiceId;
}
export type StylistId = bigint;
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export interface backendInterface {
    bookAppointment(request: BookingRequest): Promise<BookingResult>;
    cancelAppointment(referenceNumber: string): Promise<boolean>;
    claimAdmin(): Promise<boolean>;
    completeAppointment(appointmentId: AppointmentId): Promise<boolean>;
    getAdmin(): Promise<Principal>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAppointmentByReference(referenceNumber: string): Promise<Appointment | null>;
    getAvailableSlots(date: string, stylistId: StylistId): Promise<Array<TimeSlot>>;
    getServices(): Promise<Array<Service>>;
    getStylists(): Promise<Array<StylistPublic>>;
    updateServicePricing(serviceId: ServiceId, newPrice: bigint): Promise<boolean>;
    updateStylistAvailability(stylistId: StylistId, available: boolean): Promise<boolean>;
}
import type { Appointment as _Appointment, AppointmentId as _AppointmentId, AppointmentStatus as _AppointmentStatus, BookingResult as _BookingResult, ServiceId as _ServiceId, StylistId as _StylistId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bookAppointment(arg0: BookingRequest): Promise<BookingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0);
                return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0);
            return from_candid_BookingResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelAppointment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async claimAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return result;
        }
    }
    async completeAppointment(arg0: AppointmentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeAppointment(arg0);
            return result;
        }
    }
    async getAdmin(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmin();
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointmentByReference(arg0: string): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentByReference(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentByReference(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableSlots(arg0: string, arg1: StylistId): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots(arg0, arg1);
            return result;
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return result;
        }
    }
    async getStylists(): Promise<Array<StylistPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStylists();
            return result;
        }
    }
    async updateServicePricing(arg0: ServiceId, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServicePricing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServicePricing(arg0, arg1);
            return result;
        }
    }
    async updateStylistAvailability(arg0: StylistId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStylistAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStylistAvailability(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_BookingResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingResult): BookingResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppointmentId;
    startTime: string;
    status: _AppointmentStatus;
    referenceNumber: string;
    clientName: string;
    date: string;
    stylistId: _StylistId;
    createdAt: _Timestamp;
    clientEmail: string;
    clientPhone: string;
    serviceId: _ServiceId;
}): {
    id: AppointmentId;
    startTime: string;
    status: AppointmentStatus;
    referenceNumber: string;
    clientName: string;
    date: string;
    stylistId: StylistId;
    createdAt: Timestamp;
    clientEmail: string;
    clientPhone: string;
    serviceId: ServiceId;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_AppointmentStatus_n5(_uploadFile, _downloadFile, value.status),
        referenceNumber: value.referenceNumber,
        clientName: value.clientName,
        date: value.date,
        stylistId: value.stylistId,
        createdAt: value.createdAt,
        clientEmail: value.clientEmail,
        clientPhone: value.clientPhone,
        serviceId: value.serviceId
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Appointment;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Appointment;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Appointment_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
